services:
  backend:
    image: ghcr.io/timroswall/tourtap/backend:latest
    build: ./backend

  frontend:
    image: ghcr.io/timroswall/tourtap/frontend:latest
    build: ./frontend

  migrate:
    image: ghcr.io/timroswall/tourtap/migrate:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.migrate

  # seed_demo_user:
  #   image: ghcr.io/timroswall/tourtap/seed:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.seed
